@startuml

title Matrícula de Universidade


class Aluno{
    - nome: String
    - matricula: Matricula 
    - data_nascimento: date
    - endereco: String

}

class Turma{
    - ano: int
    - semestre: int
    - dia_semana: String
    - horario: String
    - sala: String
    - professor: Professor
    - aluno: Aluno

}

class Professor{
    - nome: String
    - matricula: Matricula
    - data_nascimento: date
    - carga_horaria_semanal: int
}

class Curso{
    - nome: String  
    - area: String
    - formacao: String
    - modalidade: String
    - duracao: String
    - professor: Professor
}

class Disciplina{
    - nome: String
    - carga_horaria: Float
    - turno: String
    - modalidade_disciplina: String
    - descricao: String
    - professor: Professor
    - curso: Curso

}

class Coordenador{
    


}

class Matricula{
    - : String
    - tipo: String

}

class Funcionario{
    - nome: String
    - cargo: String


}

@enduml